#!/bin/sh

INI_FILEPATH=$1
INI_FILENAME="$(basename "$INI_FILEPATH")"

SCRIPT=$(cat << SCRIPT
#!/bin/sh

# Copyright 2024 Arinze Chianumba
#
# Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
#
# -
#
# The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

# Configure the WireGuard interface
SCRIPT
)

CURRENT_SECTION=''
PEER_DESCRIPTION=''
INTERFACE_NAME=''
PEER_NAME=''
PEER_NETWORK=''
PEER_COUNT=0

while IFS='=' read -r key value || [ -n "$key" ]; do
  # Strip whitespace
  key=$(echo "$key" | tr -d '[:space:]')
  value=$(echo "$value" | tr -d '[:space:]')
  
  # Skip empty lines
  [ -z "$key" ] && continue

  # Set interface name & update section headers
  case $key in
    \#InterfaceName)
      INTERFACE_NAME="$value"
      continue
      ;;

    \[Interface\])
      CURRENT_SECTION='Interface'

      if [ -n "$INTERFACE_NAME" ]; then
        SCRIPT="$SCRIPT\nuci -q delete network.$INTERFACE_NAME\nuci set network.$INTERFACE_NAME=interface"
      else
        INTERFACE_NAME="${INI_FILENAME%.conf}"
        SCRIPT="$SCRIPT\nuci set network.$INTERFACE_NAME=interface"
      fi

      SCRIPT="$SCRIPT\nuci set network.$INTERFACE_NAME.proto='wireguard'"
      
      continue
      ;;
    
    \#Description)
      PEER_DESCRIPTION="$value"
      ;;

    \[Peer\])
      CURRENT_SECTION='Peer'
      PEER_NAME="wirguard_$INTERFACE_NAME"
      # shellcheck disable=SC1087
      PEER_NETWORK="set network.$PEER_NAME"
      PEER_COUNT=$((PEER_COUNT+1))

      SCRIPT="$SCRIPT\n\n# Configure a WireGuard peer"
      [ "$PEER_COUNT" = "1" ] && SCRIPT="$SCRIPT\nuci -q delete network.$PEER_NAME"
      
      SCRIPT="$SCRIPT\nuci set network.$PEER_NAME='$INTERFACE_NAME'\nuci $PEER_NETWORK.description='$PEER_DESCRIPTION'"
      continue
      ;;
  esac

  # Parse Interface fields
  if [ "$CURRENT_SECTION" = "Interface" ]; then
    case "$key" in
      PrivateKey)
        SCRIPT="$SCRIPT\nuci set network.$INTERFACE_NAME.private_key='$value='"
        ;;

      Address)
        SCRIPT="$SCRIPT\nuci add_list network.$INTERFACE_NAME.addresses='$value'"
        ;;

      DNS)
        SCRIPT="$SCRIPT\nuci set network.$INTERFACE_NAME.dns='$(echo "$value" | tr ',' ' ')'"
        ;;

      ListenPort)
        SCRIPT="$SCRIPT\nuci set network.$INTERFACE_NAME.listen_port='$value'"
        ;;
    esac
  fi

  # Parse peer sections
  if [ "$CURRENT_SECTION" = "Peer" ]; then
    case "$key" in
      PublicKey)
        SCRIPT="$SCRIPT\nuci $PEER_NETWORK.public_key='$value='"
        ;;

      Endpoint)
        SCRIPT="$SCRIPT\nuci $PEER_NETWORK.endpoint_host='${value%:*}'"
        SCRIPT="$SCRIPT\nuci $PEER_NETWORK.endpoint_port='${value#*:}'"
        ;;

      PersistentKeepalive)
        SCRIPT="$SCRIPT\nuci $PEER_NETWORK.persistent_keepalive='$value'"
        ;;
      
      AllowedIPs)
        SCRIPT="$SCRIPT\nuci add_list network.$PEER_NAME.allowed_ips='$(echo "$value" | tr ',' ' ')'"
        ;;

      PresharedKey)
        SCRIPT="$SCRIPT\nuci $PEER_NETWORK.preshared_key='$value'"
        ;;
    esac
  fi
done < "$INI_FILEPATH"

SCRIPT="$SCRIPT\n\n# Add interface to WAN (public) firewall zone\nuci del_list firewall.@zone[1].network='$INTERFACE_NAME'\nuci add_list firewall.@zone[1].network='$INTERFACE_NAME'\nuci commit firewall"

SCRIPT="$SCRIPT\n\n# Commit network changes\nuci commit network\n\n# Restart the network and firewall\n/etc/init.d/network restart\n/etc/init.d/firewall restart"

# Write script to file
SCRIPT_NAME="config-$INTERFACE_NAME.sh"
echo "$SCRIPT "| tee "$SCRIPT_NAME"
chmod +x "$SCRIPT_NAME"